Update main .yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -81,36 +81,39 @@ jobs:
           curl -s https://codecov.io/bash > .codecov
           chmod +x .codecov
           ./.codecov
- 
-      - name: Run robot tests
-        run: |
-            SE VALMIS SCRIPTI JUMITTI CHROMEN ASENNUKSEN KOHALLA NIIN KELASIN ET VOIS KOKEILLA ASENTAA TÄSSÄ SUORAAN
-            ELIKKÄS INSERT CHROME ASENNUS HERE: 
+      
+      - name: Robot Framework
+        uses: joonvena/robotframework-docker-action@v1.0
+      
+      # - name: Run robot tests
+      #   run: |
+      #       SE VALMIS SCRIPTI JUMITTI CHROMEN ASENNUKSEN KOHALLA NIIN KELASIN ET VOIS KOKEILLA ASENTAA TÄSSÄ SUORAAN
+      #       ELIKKÄS INSERT CHROME ASENNUS HERE: 
             
-            CHROMEDRIVERIN ASENNUS (kopioitu nanasess scriptistä):
-            CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1)
-            VERSION=$(curl --location --fail --retry 10 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
-            wget -c -nc --retry-connrefused --tries=0 https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_linux64.zip
-            unzip -o -q chromedriver_linux64.zip
-            mv chromedriver /usr/local/bin/chromedriver
-            rm chromedriver_linux64.zip
+      #       CHROMEDRIVERIN ASENNUS (kopioitu nanasess scriptistä):
+      #       CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1)
+      #       VERSION=$(curl --location --fail --retry 10 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
+      #       wget -c -nc --retry-connrefused --tries=0 https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_linux64.zip
+      #       unzip -o -q chromedriver_linux64.zip
+      #       mv chromedriver /usr/local/bin/chromedriver
+      #       rm chromedriver_linux64.zip
             
-            export DISPLAY=:0
-            chromedriver --url-base=/wd/hub &
-            sudo Xvfb -ac :0 -screen 0 1280x1024x24 > /dev/null 2>&1 &
+      #       export DISPLAY=:0
+      #       chromedriver --url-base=/wd/hub &
+      #       sudo Xvfb -ac :0 -screen 0 1280x1024x24 > /dev/null 2>&1 &
         
-            export DATABASE_URL=postgres://postgres_user:postgres_password@postgres:5432/postgres_db
-            export SECRET_KEY=cd658d476cc15a67f687760f2de8b767
+      #       export DATABASE_URL=postgres://postgres_user:postgres_password@postgres:5432/postgres_db
+      #       export SECRET_KEY=cd658d476cc15a67f687760f2de8b767
             
-            /github/home/.local/bin/poetry run python3 src/index.py &
+      #       /github/home/.local/bin/poetry run python3 src/index.py &
             
-            while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:5000/ping)" != "200" ]]; 
-              do sleep 1; 
-            done
+      #       while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:5000/ping)" != "200" ]]; 
+      #         do sleep 1; 
+      #       done
             
-            /github/home/.local/bin/poetry run robot src/tests
+      #       /github/home/.local/bin/poetry run robot src/tests
             
-            function clean_up {
-              kill $(lsof -t -i:5000)
-            }
-            trap clean_up EXIT
+      #       function clean_up {
+      #         kill $(lsof -t -i:5000)
+      #       }
+      #       trap clean_up EXIT
